order/urls.py
from django.urls import path
from .views import CustomerDeliver, changeStatus, CustomerAddressDetials, test, CreateDelivery, paymentSuccess


app_name = 'order'


urlpatterns = [
    path('deliver/all/', CustomerDeliver.as_view(), name='deliver'),
    path('deliver/<status>/', CustomerDeliver.as_view(), name='deliver'),
    path('deliver/address/<pk>/', CustomerAddressDetials.as_view(), name='address_details'),
    path('change_delivery/<pk>/', changeStatus.as_view(), name='deliver_done'),
    path('create/delivery/<id>/<pk>/<quan>/<order_type>/', CreateDelivery, name='create_delivery'),

    path('payment-successful/',paymentSuccess, name='payment-successful'),
    path('test/', test, name='test'),
]

pages/urls.py
from django.urls import path
from .views import (
    AdminPanelView, HomeView,AboutView,ContactView,ReviewPanelView, CustomerDashboard, CustomerCanceledSubscription, 
    SingleCategoryView, CancelView, ShopView, NewDashboard, ProductPriceRange, ProductAgeRange, ProductBottleSize, 
    TermsView, CustomerAddressView, CheckoutSingleAddressView, CheckoutMonthlyAddressView
)

app_name = "pages"


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('shop/price/<int:fromm>/<int:to>/', ProductPriceRange.as_view(), name='price_range'),
    path('shop/age/<int:fromm>/<int:to>/', ProductAgeRange.as_view(), name='age_range'),
    path('shop/bottle/<str:size>', ProductBottleSize.as_view(), name='size_range'),
    path('about/', AboutView.as_view(), name='about'),
    path('new/', NewDashboard.as_view(), name='new_db'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('admin_panel/', AdminPanelView.as_view(), name='admin_panel'),
    path('admin_panel/<status>/', AdminPanelView.as_view(), name='admin_panel'),
    path('review_panel/<int:id>', ReviewPanelView.as_view(), name='review_panel'),
    path('dashboard/<p_type>/', CustomerDashboard.as_view(), name='customer_dashboard'),
    path('dashboard/canceled/<sub>/', CustomerCanceledSubscription.as_view(), name='cancel_subscription'),
    
    path('category/<slug:category>/', SingleCategoryView.as_view(), name='category'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('terms', TermsView.as_view(), name='terms'),

    path('account/address/', CustomerAddressView.as_view(), name='address'),
    path('checkout/single/address/', CheckoutSingleAddressView.as_view(), name='single_address'),
    path('checkout/monthly/address/', CheckoutMonthlyAddressView.as_view(), name='monthly_address'),

]

product/urls.py
from django.urls import path
from product.views import SingleProductView, BuyNow, MonthlySubscription, FaqPageView, AddComment, EditComment
# , test, test2

app_name = "product"

urlpatterns = [
    path('single_product/<int:id>', SingleProductView.as_view(), name='single_product'),
    path('add-comment/', AddComment.as_view(), name='add_comment'),
    path('edit-comment/', EditComment.as_view(), name='edit_comment'),

    path('Buy-Now/<int:p>/<int:q>/', BuyNow.as_view(), name='buy-now'),
    path('Monthly/<int:p>/<int:q>/', MonthlySubscription.as_view(), name='monthly'),
    path('faq/', FaqPageView.as_view(), name='faq'),

    # path('test/', test, name='test'),
    # path('test2/<video_id>/', test2, name='test2'),
]

templates/new_template/dashboard/address.html
{% extends 'new_template/base.html' %}
{% block newMain %}


        <div class="container d-flex justify-content-center">
            <div class="row ">
                <br>
                <div class="row d-flex justify-content-center">
                   
                    {% if subs == "true" %}

                        <div id="login-form" >
                            <form class="col-12 p-2 " action="{% url 'pages:sub_address' %}" method="POST">
                                {% csrf_token %}
                                <p class="text-center text-muted my-2">
                                    Please mention address to deliver the product 
                                </p>
                                <div class="row d-flex justify-content-center">
                                    <div class="col-12 d-flex justify-content-center">
                                        <div class="col-3 d-flex justify-content-center">
                                            <input class="form-input col-12 my-1" type="text" name="name" placeholder="Name" required>  <br>
                                        </div>
                                    </div>
                                    
                                    <div class="col-12 d-flex justify-content-center">
                                        <div class="col-3 d-flex justify-content-center">
                                            <input class="form-input col-12 my-1" type="text" name="country" placeholder="Country" required>  <br>
                                        </div>
                                    </div>
                                    
                                    <div class="col-12 d-flex justify-content-center">
                                        <div class="col-3 d-flex justify-content-center">
                                            <input class="form-input col-12 my-1" type="text" name="address_1" placeholder="Address Line 1" required>  <br>
                                        </div>
                                    </div>
                                    
                                    <div class="col-12 d-flex justify-content-center">
                                        <div class="col-3 d-flex justify-content-center">
                                            <input class="form-input col-12 my-1" type="text" name="address_2" placeholder="Address Line 2" >  <br>
                                        </div>
                                    </div>

                                    <div class="col-12 d-flex justify-content-center">
                                        <div class="col-3 d-flex justify-content-center">
                                            <input class="form-input col-12 my-1" type="text" name="city" placeholder="City" required> <br>
                                        </div>
                                    </div>

                                    <div class="col-12 d-flex justify-content-center">
                                        <div class="col-3 d-flex justify-content-center">
                                            <input class="form-input col-12 my-1" type="text" name="state" placeholder="State" required> <br>
                                        </div>
                                    </div>

                                    <div class="col-12 d-flex justify-content-center">
                                        <div class="col-3 d-flex justify-content-center">
                                            <input class="form-input col-12 my-1" type="number" name="contact" placeholder="Phone Number" required> <br>
                                        </div>
                                    </div>

                                    <input type="hidden" name="sub_id" value="{{id}}"> <br>
                                    <input type="hidden" name="prod_id" value="{{pk}}"> <br>
                                    <input type="hidden" name="prod_quan" value="{{quan}}"> <br>
                                    <a href="" class="text-center col-12"><button type="submit" class="btn-login text-center fw-bold ">Submit</button></a>
                                    
                                </div>
                            </form>
                        </div>

                    {% elif subs == "false" %}
                        
                        <div id="login-form" >
                            <form class="col-12 p-2 " action="{% url 'pages:single_address' %}" method="POST">
                                {% csrf_token %}
                                <p class="text-center text-muted my-2">
                                    Please mention address to deliver the product 
                                </p>
                                <div class="row d-flex justify-content-center">
                                    <div class="col-12 d-flex justify-content-center">
                                        <div class="col-3 d-flex justify-content-center">
                                            <input class="form-input col-12 my-1" type="text" name="name" placeholder="Name" required>  <br>
                                        </div>
                                    </div>
                                    
                                    <div class="col-12 d-flex justify-content-center">
                                        <div class="col-3 d-flex justify-content-center">
                                            <input class="form-input col-12 my-1" type="text" name="country" placeholder="Country" required>  <br>
                                        </div>
                                    </div>
                                    
                                    <div class="col-12 d-flex justify-content-center">
                                        <div class="col-3 d-flex justify-content-center">
                                            <input class="form-input col-12 my-1" type="text" name="address_1" placeholder="Address Line 1" required>  <br>
                                        </div>
                                    </div>
                                    
                                    <div class="col-12 d-flex justify-content-center">
                                        <div class="col-3 d-flex justify-content-center">
                                            <input class="form-input col-12 my-1" type="text" name="address_2" placeholder="Address Line 2" >  <br>
                                        </div>
                                    </div>

                                    <div class="col-12 d-flex justify-content-center">
                                        <div class="col-3 d-flex justify-content-center">
                                            <input class="form-input col-12 my-1" type="text" name="city" placeholder="City" required> <br>
                                        </div>
                                    </div>

                                    <div class="col-12 d-flex justify-content-center">
                                        <div class="col-3 d-flex justify-content-center">
                                            <input class="form-input col-12 my-1" type="text" name="state" placeholder="State" required> <br>
                                        </div>
                                    </div>

                                    <div class="col-12 d-flex justify-content-center">
                                        <div class="col-3 d-flex justify-content-center">
                                            <input class="form-input col-12 my-1" type="number" name="contact" placeholder="Phone Number" required> <br>
                                        </div>
                                    </div>

                                    <input type="hidden" name="single_id" value="{{id}}"> <br>
                                    <input type="hidden" name="prod_id" value="{{pk}}"> <br>
                                    <input type="hidden" name="prod_quan" value="{{quan}}"> <br>
                                    <a href="" class="text-center col-12"><button type="submit" class="btn-login text-center fw-bold ">Submit</button></a>
                                    
                                </div>
                            </form>
                        </div>

                    {% endif %}

                </div>
            </div>
        </div>


{% endblock newMain %}

templates/new_template/dashboard/admin_dashboard.html
{% extends 'new_template/base.html' %}
{% block newMain %}

    {% if class_active == "single" %}

        <div class="container" style="overflow-x:auto; font-size:80%">
            <div class="row ">
                <br>
                <h1 class=" fw-bold text-dark my-3 text-center">
                    Single Item Report Admin 
                </h1>
                        
                <table class="table ps-table ps-table--vendor">
                    <thead>
                        <tr>
                            <th>Created</th>
                            <th>Product</th>
                            <th>Price</th>
                            <th>Qunatity</th>
                            <th>Total</th>
                            <th>Status</th>
                        </tr>
                    </thead>

                    {% for r in single %}

                        <tbody>

                            <tr>
                                <td>{{r.current_period_start}}</td>
                                <td>{{r.product.product_name}}</td>
                                <td>${{r.amount}}</td>
                                <td>{{r.quantity}}</td>
                                <td>${{r.total}}</td>
                                <td style="color:green"> {{r.status}} </td>

                            </tr>

                        </tbody>

                    {% endfor %}


                </table>
            </div>
        </div>

    {% else %}

        <div class="container" style="overflow-x:auto; font-size:80%">
            <div class="row">
                <br>
                <h1 class="fw-bold text-dark my-3 text-center">
                    Subscription Report For Admin 
                </h1>
                    
                <table class="table ps-table ps-table--vendor">
                    <thead>
                        <tr>
                            <th>User</th>
                            <th>Date</th>
                            <th>Interval</th>
                            <th>Product</th>
                            <th>Price x Qunatity</th>
                            <th>Total</th>
                            <th>Next Invoice</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    
                    {% for r in subscription %}
                        <tbody>
                                <tr>
                                    <td>{{r.user}}</td>
                                    <td>{{r.current_period_start}}</td>
                                    <td>{{r.interval}}</td>
                                    <td>{{r.product}}</td>
                                    <td>${{r.amount}} x {{r.quantity}}</td>
                                    <td>${{r.total}}</td>
                                    <td>{{r.current_period_end}}</td>
                                    
                                    {% if r.status == "active" %}
                                        <td style="color:green">{{r.status|upper}}</td>
                                    {% else %}
                                        <td style="color:red">{{r.status|upper}}</td>
                                    {% endif %}
                                </tr>
                        </tbody>

                    {% endfor %}
                </table>
            </div>
        </div>

    {% endif %}


    <script>
        function checkdel(){
            return confirm('Are you sure you want to cancel the subscription? \n\nNote:- Once you canceled it cannot be reversed');
        }
    </script>


{% endblock newMain %}

templates/new_template/dashboard/checkout_redirect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body onload="document.forms['checkout_redirect'].submit()">

    <form action="{% url 'order:payment-successful' %}" method="post" name="checkout_redirect">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{id}}">
        <input type="hidden" name="order_type" value="{{order_type}}">
    </form>
    
</body>
</html>

templates/new_template/dashboard/customer_account.html
{% extends 'new_template/base.html' %}
{% block newMain %}
{% load static %}

<div id="account-info" class="container d-flex justify-content-center my-3 min-h-100">
    <div class="my-auto">
        <form class="py-2 mx-auto" action="" method="POST">
            {% csrf_token %}
            <div>
                <h1 class=" fw-bold text-white my-3 text-center">
                    Your Account <br />info
                </h1>
                <p class="text-center text-white my-2">
                    Set up your account to complete your purchase.
                </p>

                {% if messages %}
                    {% for message in messages %}
                        <p class="text-center my-2" style="color:yellow">
                            {{message}}.
                        </p>
                    {% endfor %}
                {% endif %}

                <div class="row d-flex justify-content-center">

                    <div class="row my-1">
                        {% for form in form %}
                            <div class="col-12 col-md-6 ">
                                <h3 class="text-white fw-bold text-center">{{form.label}}</h3>
                                <div class="d-flex justify-content-center">
                                    {{form}}
                                </div>
                                <p class="fw-bold text-center" style="color:red;">{{form.errors|striptags}}</p>
                            </div>
                        {% endfor %}
                        
                    </div>

                    {% if product and quantity %}
                        <input type="hidden" name="product" value="{{product}}"> <br>
                        <input type="hidden" name="quantity" value="{{quantity}}"> <br>
                    {% endif %}

                    <a href="#" class="text-center my-3 col-12"><button type="submit" class="btn-2 text-center fw-bold ">Save Info <span><i class=" ms-2 fas fa-save"></i></span></button></a>
                    
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock newMain %}

templates/new_template/dashboard/customer_dashboard.html
{% extends 'new_template/base.html' %}
{% block newMain %}

    {% if single_item == "false" %}

        <div class="container" style="overflow-x:auto; font-size:80%">
            <div class="row">
                <br>
                <h1 class="fw-bold text-dark my-3 text-center">
                    Subsription Report 
                </h1>
                        
                <table class="table ps-table ps-table--vendor">
                    <thead>
                        <tr>
                            <th>Subscription</th>
                            <th>Product</th>
                            <th>Price</th>
                            <th>Qunatity</th>
                            <th>Total</th>
                            <th>Next Invoice</th>
                            <th>Status</th>
                            <th>Delivery </th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    {% for r in subscription %}

                        <tbody>
                            <tr>
                                <td>{{r.current_period_start}}</td>
                                <td> <a href="{% url 'product:single_product' r.product.pk %}"> {{r.product}} </a> </td>
                                <td>${{r.amount}}</td>
                                <td>{{r.quantity}}</td>
                                <td>${{r.total}}</td>
                                <td>{{r.current_period_end}}</td>
                            
                                {% if r.status == "active" %}
                                    <td style="color:green">{{r.status|upper}}</td>
                                {% else %}
                                    <td style="color:red">{{r.status|upper}}</td>
                                {% endif %}

                                <td>{{r.delivery.delivery}} </td>
                            
                                {% if r.status == "active" %}
                                    <td> <a href="{% url 'pages:cancel_subscription' r.id %}" onclick='return checkdel()'> Change </a></td>
                                {% elif r.status == "canceled" %}
                                    <td>-</td>
                                {% endif %}

                            </tr>
                        </tbody>

                    {% endfor %}


                </table>
            </div>
        </div>

    {% elif single_item == "true" %}

        <div class="container" style="overflow-x:auto; font-size:80%">
            <div class="row ">
                <br>
                <h1 class=" fw-bold text-dark my-3 text-center">
                    Single Item Report 
                </h1>
                    
                <table class="table ps-table ps-table--vendor">
                    <thead>
                        <tr>
                            <th>Created</th>
                            <th>Product</th>
                            <th>Price</th>
                            <th>Qunatity</th>
                            <th>Total</th>
                            <th>Delivery </th>
                        </tr>
                    </thead>

                    {% for r in single %}

                        <tbody>
                            <tr>
                                <td>{{r.current_period_start}}</td>
                                <td> <a href="{% url 'product:single_product' r.product.pk %}"> {{r.product}} </a> </td>
                                <td>${{r.amount}}</td>
                                <td>{{r.quantity}}</td>
                                <td>${{r.total}}</td>
                                <td>{{r.delivery.delivery}} </td>
                            </tr>
                        </tbody>

                    {% endfor %}


                </table>
            </div>
        </div>

    {% endif %}


    <script>
        function checkdel(){
            return confirm('Are you sure you want to cancel the subscription? \n\nNote:- Once you canceled it cannot be reversed');
        }
    </script>


{% endblock newMain %}

templates/new_template/dashboard/delivery.html
{% extends 'new_template/base.html' %}
{% block newMain %}


    <div class="container" style="overflow-x:auto; font-size:80%">
        <div class="row">
            <br>
            <h1 class=" fw-bold text-dark my-3 text-center">
                Delivery Report 
            </h1>
                
            <table class="table ps-table ps-table--vendor">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Name</th>
                        <th>Details</th>
                        <th>Action</th>
                    </tr>
                </thead>

                {% for r in items %}

                    <tbody>
                        <tr>
                            <td> {{r.date}}</td>
                            <td> {{r.address}}</td>
                            <td> <a href="{% url 'order:address_details' r.pk %}"> View Details </a> </td>
                            <td>
                                <form action="{% url 'order:deliver_done' r.pk %}" method="POST">
                                    {% csrf_token %}
                                    <select name="status" onchange=' this.form.submit(); '>
                                        <option value='undelivered' {% if r.delivery == "undelivered" %} {{"selected"}} {% endif %} >undelivered</option>
                                        <option value='delivered' {% if r.delivery == "delivered" %} {{"selected"}} {% endif %} >delivered</option>
                                    </select>
                                </form> 
                            </td>

                        </tr>
                    </tbody>

                {% endfor %}


            </table>
                
            </div>
        </div>
    </div>


{% endblock newMain %}

templates/new_template/dashboard/order_details.html
{% extends 'new_template/base.html' %}
{% block newMain %}


    <br>
    <div class="container d-flex justify-content-center">
        <div class="row ">

            <div class="ps-contact-info">
                <div class="container">
                    <div class="ps-section__content">
                        <div class="row">
                            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-12 ">
                                <div class="ps-block--contact-info">
                                    <h4>Name</h4>
                                    <p><span>{{item.address.fname|title}} {{item.address.lname|title}}</span></p>
                                </div>
                            </div>
                            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-12 ">
                                <div class="ps-block--contact-info">
                                    <h4>Country</h4>
                                    <p><span>{{item.address.country|title}}</span></p>
                                </div>
                            </div>
                            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-12 ">
                                <div class="ps-block--contact-info">
                                    <h4>Address No 1</h4>
                                    <p><span>{{item.address.address_1|title}}</span></p>
                                </div>
                            </div>
                            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-12 ">
                                <div class="ps-block--contact-info">
                                    <h4>Address No 2</h4>
                                    <p><span>{{item.address.address_2|title}}</span></p>
                                </div>
                            </div>
                            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-12 ">
                                <div class="ps-block--contact-info">
                                    <h4>City</h4>
                                    <p><span>{{item.address.city|title}}</span></p>
                                </div>
                            </div>
                            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-12 ">
                                <div class="ps-block--contact-info">
                                    <h4>State</h4>
                                    <p><span>{{item.address.state|title}}</span></p>
                                </div>
                            </div>
                            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-12 ">
                                <div class="ps-block--contact-info">
                                    <h4>Contact</h4>
                                    <p><span>{{item.address.contact|title}}</span></p>
                                </div>
                            </div>
                            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-12 ">
                                <div class="ps-block--contact-info">
                                    <h4>Product</h4>
                                    <p><span>{{item.product|title}}</span></p>
                                </div>
                            </div>
                            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 col-12 ">
                                <div class="ps-block--contact-info">
                                    <h4>Quantity</h4>
                                    <p><span>{{item.quantity|title}}</span></p>
                                </div>
                            </div>
                            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 ">
                                <div class="ps-block--contact-info text-center">
                                    <h4>Delivery</h4>
                                    {% if item.delivery == "delivered" %}
                                        <p style="color:green"><span>{{item.delivery|title}}</span></p>
                                    {% else %}
                                        <p style="color:red"><span>{{item.delivery|title}}</span></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>



{% endblock newMain %}