order/urls.py
from django.urls import path
from .views import CustomerDeliver, changeStatus, CustomerAddressDetials, test, CreateDelivery, paymentSuccess


app_name = 'order'


urlpatterns = [
    path('deliver/all/', CustomerDeliver.as_view(), name='deliver'),
    path('deliver/<status>/', CustomerDeliver.as_view(), name='deliver'),
    path('deliver/address/<pk>/', CustomerAddressDetials.as_view(), name='address_details'),
    path('change_delivery/<pk>/', changeStatus.as_view(), name='deliver_done'),
    path('create/delivery/<id>/<pk>/<quan>/<order_type>/', CreateDelivery, name='create_delivery'),

    path('payment-successful/',paymentSuccess, name='payment-successful'),
    path('test/', test, name='test'),
]

pages/urls.py
from django.urls import path
from .views import (
    AdminPanelView, HomeView,AboutView,ContactView,ReviewPanelView, CustomerDashboard, CustomerCanceledSubscription, 
    SingleCategoryView, CancelView, ShopView, NewDashboard, ProductPriceRange, ProductAgeRange, ProductBottleSize, 
    TermsView, CustomerAddressView, CheckoutSingleAddressView, CheckoutMonthlyAddressView
)

app_name = "pages"


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('shop/price/<int:fromm>/<int:to>/', ProductPriceRange.as_view(), name='price_range'),
    path('shop/age/<int:fromm>/<int:to>/', ProductAgeRange.as_view(), name='age_range'),
    path('shop/bottle/<str:size>', ProductBottleSize.as_view(), name='size_range'),
    path('about/', AboutView.as_view(), name='about'),
    path('new/', NewDashboard.as_view(), name='new_db'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('admin_panel/', AdminPanelView.as_view(), name='admin_panel'),
    path('admin_panel/<status>/', AdminPanelView.as_view(), name='admin_panel'),
    path('review_panel/<int:id>', ReviewPanelView.as_view(), name='review_panel'),
    path('dashboard/<p_type>/', CustomerDashboard.as_view(), name='customer_dashboard'),
    path('dashboard/canceled/<sub>/', CustomerCanceledSubscription.as_view(), name='cancel_subscription'),
    
    path('category/<slug:category>/', SingleCategoryView.as_view(), name='category'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('terms', TermsView.as_view(), name='terms'),

    path('account/address/', CustomerAddressView.as_view(), name='address'),
    path('checkout/single/address/', CheckoutSingleAddressView.as_view(), name='single_address'),
    path('checkout/monthly/address/', CheckoutMonthlyAddressView.as_view(), name='monthly_address'),

]

product/urls.py
from django.urls import path
from product.views import SingleProductView, BuyNow, MonthlySubscription, FaqPageView, AddComment, EditComment
# , test, test2

app_name = "product"

urlpatterns = [
    path('single_product/<int:id>', SingleProductView.as_view(), name='single_product'),
    path('add-comment/', AddComment.as_view(), name='add_comment'),
    path('edit-comment/', EditComment.as_view(), name='edit_comment'),

    path('Buy-Now/<int:p>/<int:q>/', BuyNow.as_view(), name='buy-now'),
    path('Monthly/<int:p>/<int:q>/', MonthlySubscription.as_view(), name='monthly'),
    path('faq/', FaqPageView.as_view(), name='faq'),

    # path('test/', test, name='test'),
    # path('test2/<video_id>/', test2, name='test2'),
]

templates/new_template/footer.html
{% load static %}
<footer>
    <div class="container-fluid bg-black py-5">
        <div class="container">
            <div class="row d-flex justify-content-around">
                <div class="col-12 col-md-6 mt-3">
                    <h1 class="fw-bold text-white my-2">Start your adventure</h1>
                </div>
                <div class="col-12 col-md-6 my-3">
                    <div class="d-flex justify-content-around mt-3">
                        <div>
                            {% if not user.is_authenticated %}
                                <a href="{% url 'register' %}"><button class="btn-1 fw-bold">JOIN CLUB</button></a>
                            {% endif %}
                        </div>
                        <div>
                            <a href="{% url 'pages:shop' %}"><button class="btn-1 fw-bold">SHOP</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-black">
        <div class="container footer mb-3">
            <h1 class="fw-bold text-white mb-3">
                A WHISKY CLUB FOR THE CURIOUS
            </h1>
        </div>
        <div>
            <div id="footer-items" class="row">
                <div class="col-6 col-md-2">
                    <ul>
                        <li><a href="#" class="text-white fw-bold">ABOUT THE CLUB</a></li>
                        <li><a href="{% url 'pages:terms' %}" class="text-white fw-bold">TERMS</a></li>
                        <li><a href="#" class="text-white fw-bold">FAQ / CONTACT</a></li>
                    </ul>
                </div>
                
                <div class="col-6 col-md-2">
                    <ul>
                        {% if user.is_authenticated and not user.is_superuser %}
                            <li><a href="#" class="text-white fw-bold">Subscription</a></li>
                            <li><a href="#" class="text-white fw-bold">Single</a></li>
                        {% endif %}
                    </ul>
                </div>
                <div class="col-6 col-md-2">
                    <ul>
                        <li><a href="#" class="text-white fw-bold">INSTAGRAM</a></li>
                        <li><a href="#" class="text-white fw-bold">FACEBOOK</a></li>
                        <li><a href="#" class="text-white fw-bold">TWITTER</a></li>
                        <li><a href="#" class="text-white fw-bold">YOUTUBE</a></li>
                    </ul>
                </div>
                {% comment %} <div class="d-flex fw-bold text-white justify-content-end">
                    © 2021 WHISKYME
                </div> {% endcomment %}
            </div>
        </div>
    </div>
</footer>

templates/new_template/header.html
{% load static %}
<header id="header" class="bg-black">
    <nav class="navbar navbar-expand-lg  px-2">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'pages:home' %}"><img src="{% static 'new_static/assets/imgs/wiskey-logo.png' %}" alt="wiskey-logo" class="img-fluid logo" /></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainnavigation" aria-controls="mainnavigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="fa fa-bars text-secondary justify-content-end"></span>
            </button>
            <div class="collapse navbar-collapse" id="mainnavigation">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-2 ms-lg-5 left fw-bold ">
                    
                    {% if user.is_superuser %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Subscription
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item {% if class_active == "all" %} active {% endif %}" href="{% url 'pages:admin_panel' "all" %}">All</a>
                            <a class="dropdown-item {% if class_active == "active" %} active {% endif %}" href="{% url 'pages:admin_panel' "active" %}">Active</a>
                            <a class="dropdown-item {% if class_active == "unpaid" %} active {% endif %}" href="{% url 'pages:admin_panel' "unpaid" %}">Unpaid</a>
                            <a class="dropdown-item {% if class_active == "single" %} active {% endif %}" href="{% url 'pages:admin_panel' "single" %}">Single</a>
                            <a class="dropdown-item {% if class_active == "canceled" %} active {% endif %}" href="{% url 'pages:admin_panel' "canceled" %}">Cancelled</a>
                            
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Delivery
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item {% if class_active == "all" %} active {% endif %}" href="{% url 'order:deliver' %}">All</a>
                                <a class="dropdown-item {% if class_active == "delivered" %} active {% endif %}" href="{% url 'order:deliver' "delivered" %}">Delivered</a>
                                <a class="dropdown-item {% if class_active == "undelivered" %} active {% endif %}" href="{% url 'order:deliver' "undelivered" %}">Not Delivered</a>
                            </div>
                        </li>

                    {% endif %}
                    
                    {% if not user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link ms-2" href="{% url 'pages:shop' %}">Shop</a>
                        </li>
                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link ms-2" href="{% url 'pages:about' %}">About</a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link ms-2" href="{% url 'product:faq' %}">FAQ</a>
                    </li>
                    
                </ul>
                <ul class="navbar-nav ms-lg-auto mb-2 mb-lg-0  ms-lg-0">
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            {% if not user.is_superuser %}
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Dashboard
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item {% if myaccount == "true" %} active {% endif %}" href="{% url 'pages:address' %}" class="text-white">My Account</a>
                                        <a class="dropdown-item {% if single_item == "false" %} active {% endif %}" href="{% url 'pages:customer_dashboard' "subscription" %}" class="text-white">Subscription</a>
                                        <a class="dropdown-item {% if single_item == "true" %} active {% endif %}" href="{% url 'pages:customer_dashboard' "single" %}" class="text-white">Single</a>
                                    </div>
                                </li>
                            {% endif %}
                            
                            <a href="{% url 'logout' %}"><button class="btn-4">Logout</button></a>
                        {% else %}
                            <a class="nav-link" href="{% url 'login' %}">
                                <p>Already have an <br /> account? <ins>SIGN IN</ins></p>
                            </a>
                        {% endif %}
                    </li>
                        {% if not user.is_authenticated %}
                            <li class="nav-item my-auto ms-2">
                                <a href="{% url 'register' %}"><button class="btn-4">JOIN CLUB</button></a>
                            </li>
                        {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/new_template/payment-sucessful.html
{% extends 'new_template/base.html' %}
{% block newMain %}


<style type="text/css">
    /*payment-sucessful*/
    .payment-sucessful-wrapper{
    -webkit-box-shadow: 0px 9px 62px -9px rgba(0,0,0,0.31);
    -moz-box-shadow: 0px 9px 62px -9px rgba(0,0,0,0.31);
    box-shadow: 0px 9px 62px -9px rgba(0,0,0,0.31);
    border-radius: 20px;

    }
    @media (min-device-width: 768px) {
         .payment-sucessful-wrapper{
    -webkit-box-shadow: 0px 9px 62px -9px rgba(0,0,0,0.31);
    -moz-box-shadow: 0px 9px 62px -9px rgba(0,0,0,0.31);
    box-shadow: 0px 9px 62px -9px rgba(0,0,0,0.31);
    border-radius: 20px;
    min-width: 80vh;
    }

    }
</style>


<div class="container-fluid min-h-100 d-flex justify-content-center align-items-center my-2" id="payment-sucessful-wrapper">
    <div class="row">
        <div class="payment-sucessful-wrapper p-0">
            <div class="payment-sucessful-inner p-4 p-md-5 ">
                <div>
                    <h3 class="fw-bold text-center text-orange my-3">
                        Payment Sucessful!
                    </h3>
                    <h1 class="fw-bold text-center text-orange my-3">
                        <i class="far fa-check-circle"></i>
                    </h1>
                </div>
                <div class="row d-flex justify-content-center">
                    <div>
                        <div class="row my-2">
                            <div class="col-12 col-md-6">
                                <h6>Name</h6>
                            </div>
                            <div class="col-12 col-md-6 d-flex justify-content-end">
                                <h6 class=" text-black fw-bold">{{name}}</h6>
                            </div>
                        </div>
                        
                        
                        
                        <div class="row my-2">
                            <div class="col-12 col-md-6">
                                <h6>Email</h6>
                            </div>
                            <div class="col-12 col-md-6 d-flex justify-content-end">
                                <h6 class=" text-black fw-bold">{{email}}</h6>
                            </div>
                        </div>
                        <div class="row my-2">
                            <div class="col-12 col-md-6">
                                <h6>Product</h6>
                            </div>
                            <div class="col-12 col-md-6 d-flex justify-content-end">
                                <h6 class=" text-black fw-bold">{{product}}</h6>
                            </div>
                        </div>
                        <div class="row my-2">
                            <div class="col-12 col-md-6">
                                <h6>Quantity</h6>
                            </div>
                            <div class="col-12 col-md-6 d-flex justify-content-end">
                                <h6 class=" text-black fw-bold">{{quantity}}</h6>
                            </div>
                        </div>
                        <div class="row my-4">
                            <div class="col-12 col-md-6">
                                <p class="text-black fw-bold">Amount Paid</p>
                            </div>
                            <div class="col-12 col-md-6 d-flex justify-content-end">
                                <h4 class=" text-black fw-bold">£{{amount}}</h4>
                            </div>
                        </div>
                        
                        <div class="d-flex justify-content-around my-3">
                            <div>
                                <a href="{% url 'pages:customer_dashboard' order_type %}"><button class="btn-4 fw-bold">Dashboard</button></a>
                            </div>
                        </div>
                        <div class="d-flex fw-bold text-black justify-content-center">
                            © 2022 WHISKYME
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">(function(){window['__CF$cv$params']={r:'6d59f4fb1acec609',m:'WnTa0r9HLx1LJvIZx5le.8XAsxrJNNtRrGHjNTc2k8Y-1643537914-0-AXulNmksL0qrpY1ZAxKLkCiKNbqSNwIUH9QWySeN+lrr7IrIEQOGExuO6m3B6VEApPqWGBWsu5Jmwha6GHkF37KKlgvj7VYCWPzl+MBSJfghl37c1I03gErnBD75hF44Ta/LklJFejOzoVGK+/NM3JE5uLEuVZir2GdPeY6i4Z7LSsLOmXWwXXE55Ug0GUI6rYCM8uO4RiFSBkIu2Wu9rlc=',s:[0xc450da8e82,0x2c74c39bc0],}})();</script></body>



{% endblock newMain %}

templates/new_template/shop.html

{% extends 'new_template/base.html' %}
{% load static %}

{% block newMain %}

<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 bg-black">
            <img src="{% static 'new_static/assets/imgs/shop.jpg' %}" class="img-fluid">
        </div>
        <div class="col-12 col-md-6 bg-black fw-bold text-white d-flex justify-content-center align-items-center">
            <div class="fw-bold text-white text-center">
                <h1 class="text-white fw-bold">
                    The Cellar
                </h1>
                <p>
                    All of our past and present whiskies <br /> available to purchase in one place.<br /> Refine the collection by flavour,<br /> region or distillery to hone in on<br /> your perfect dram.
                </p>
            </div>
        </div>
        <div class="bg-orange text-black fw-bold py-1 mb-3">
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#product-navigation" aria-controls="mainnavigation" aria-expanded="false" aria-label="Toggle navigation">
                        <h3 class="text-white fw-bold"><b>More Whiskeys</b>   <span>  <i class="fas fa-wine-bottle"></i></span></h3>
                    </button>
                    <div class="collapse navbar-collapse" id="product-navigation">
                        <ul class="navbar-nav d-flex justify-content-between fw-bold ">
                            <li class="nav-item">
                                <a class="nav-link text-black fw-bold" href="{% url 'pages:shop' %}" class="text-white"><ins>ALL WHISKIES</ins></a>
                            </li>
                           
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>

<div class="container">
    <div class="row d-flex justify-content-between">
        <div class="col-12 col-md-6 col-lg-3">
            <div id="filter">
                <div class="border-0">
                    <h2 class="accordion-header" id="filter-dropdown">
                        <button class="filter-button mb-3 " type="button" data-bs-toggle="collapse" data-bs-target="#filter-body" aria-expanded="false" aria-controls="filter-body">
                            <h5 class="my-auto fw-bold">filter<span><i class="ms-3 fas fa-arrow-down"></i></span></h5>
                        </button>
                    </h2>
                    <div id="filter-body" class="accordion-collapse 
                        collapse" aria-labelledby="filter-dropdown" data-bs-parent="#filter">
                        <div id="price">
                            <div class="accordian-header-box border-0">
                                <h2 class="accordion-header" id="price-dropdown">
                                    <button class="accordian-header-box" type="button" data-bs-toggle="collapse" data-bs-target="#price-body" aria-expanded="false" aria-controls="price-body">
                                        <h5 class="my-auto fw-bold">price</h5>
                                    </button>
                                </h2>
                                <div id="price-body" class="accordion-collapse 
                                    collapse" aria-labelledby="price-dropdown" data-bs-parent="#price">
                                    <div class="accordion-body p-0 ">
                                        <button class="filter-button-inside my-1 ">
                                            <a href="{% url 'pages:price_range' "0" "100" %}">under £100 </a>
                                        </button><br />
                                        <button class="filter-button-inside my-1 ">
                                            <a href="{% url 'pages:price_range' "100" "250" %}">£100 - £250 </a>
                                        </button><br />
                                        <button class="filter-button-inside my-1 ">
                                           <a href="{% url 'pages:price_range' "250" "500" %}"> £250 - £500 </a>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                     
                        <div id="AGE">
                            <div class="accordian-header-box border-0">
                                <h2 class="accordion-header" id="AGE-dropdown">
                                    <button class="accordian-header-box" type="button" data-bs-toggle="collapse" data-bs-target="#AGE-body" aria-expanded="false" aria-controls="AGE-body">
                                        <h5 class="my-auto fw-bold">AGE</h5>
                                    </button>
                                </h2>
                                <div id="AGE-body" class="accordion-collapse 
                                    collapse" aria-labelledby="AGE-dropdown" data-bs-parent="#AGE">
                                    <div class="accordion-body p-0 ">
                                        <button class="filter-button-inside my-1 ">
                                            <a href="{% url 'pages:age_range' "0" "10" %}">under 10 years </a>
                                        </button><br />
                                        <button class="filter-button-inside my-1 ">
                                            <a href="{% url 'pages:age_range' "10" "25" %}">10 - 25 years </a>

                                            
                                        </button><br />
                                        <button class="filter-button-inside my-1 ">
                                            <a href="{% url 'pages:age_range' "25" "50" %}">25 - 50 years </a>

                                            
                                        </button><br />
                                        <button class="filter-button-inside my-1 ">
                                            <a href="{% url 'pages:age_range' "50" "75" %}">50 - 75 years </a>

                                            
                                        </button><br />
                                        <button class="filter-button-inside my-1 ">
                                            <a href="{% url 'pages:age_range' "75" "200" %}">75 - 200 years </a>
                                            
                                        </button><br />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="FLAVOUR" class="mb-2">
                            <div class="accordian-header-box border-0">
                                <h2 class="accordion-header" id="FLAVOUR-dropdown">
                                    <button class="accordian-header-last" type="button" data-bs-toggle="collapse" data-bs-target="#FLAVOUR-body" aria-expanded="false" aria-controls="FLAVOUR-body">
                                        <h5 class="my-auto fw-bold">Bottle Size</h5>
                                    </button>
                                </h2>
                                <div id="FLAVOUR-body" class="accordion-collapse 
                                    collapse" aria-labelledby="FLAVOUR-dropdown" data-bs-parent="#FLAVOUR">
                                    <div class="accordion-body p-0 ">
                                        <a href="{% url 'pages:size_range' "5cl" %}"> <button class="flavor-button-1 border-0 my-1 ">
                                            5cl
                                        </button><br /></a>
                                    </div>
                                    <div class="accordion-body p-0 ">
                                        <a href="{% url 'pages:size_range' "70cl" %}"> <button class="flavor-button-2 border-0 my-1 ">
                                            70cl
                                        </button><br /></a>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-3">
            <!-- <p>search </p> -->
        </div>
    </div>
</div>

<div id="shop-product" class="container mb-3">
    <div class="row">
        <div class="col-12 col-md-6">
            <div class="bg-yellow border-radius p-3">
                <div class="row">
                    <div class="col-12 col-md-6">
                        <div class="text-black fw-bold">
                            <h3 class="text-black fw-bold mb-3">
                                Want a little more?
                            </h3>
                            <p class="fw-bold mb-2">
                                We are now stocking 6cl pouches alongside full size bottles of all the whiskies we send our members from Sep '21 onwards. Perfect if you want a little more or if you missed a past whisky.
                            </p>
                        </div>
                    </div>
                    <div class="col-12 col-md-6 order-1">
                        <img src="{% static 'new_static/assets/imgs/pouch.png' %} " class="img-fluid">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-md-6">
            <div class="bg-black border-radius p-5 ">
                <div class="row">
                    <div class="col-12 col-md-6 ">
                        <div class="text-black fw-bold">
                            <h2 class="text-white fw-bold mb-5">
                                Our First World <br />
                                Whisky Awaits...
                            </h2>
                            <p class="fw-bold mb-1 text-white">
                                Bulleit 95 Rye
                            </p>
                            <a href="{% url 'pages:shop' %}"><button class="btn-1 fw-bold mt-3">SHOP</button></a>
                        </div>
                    </div>
                    <div class="col-12 col-md-6 order-1 d-flex justify-content-center my-2">
                        <img src="{% static 'new_static/assets/imgs/bulleit.png' %} " class="img-fluid">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">

        {% for product in product %}
            <div class="col-12  col-md-6 col-lg-3">
                <div class="product-wrapper p-2">
                    <div class="d-flex justify-content-center">
                        <div class="img-product-wrapper my-3">
                            <img src="{{product.picture.url}}" class="img-product-wrapper">
                        </div>
                    </div>
                    <div>
                        <h5 class="text-black fw-bold text-center" style="font-size:15px">{{product.product_name|truncatewords:3}}</h5>
                        <p class="my-2">
                            {{product.category}}
                        </p>
                        <h5 class="fw-bold text-black">
                            £{{product.price}}
                        </h5>
                        <div class="d-flex justify-content-end">
                            <a href="{% url 'product:single_product' product.pk %}"><button class="btn-3 fw-bold">View Details</button></a> 
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
   
</div>


{% endblock newMain %}